#ifndef __DESIGN_KERNEL_H__
#define __DESIGN_KERNEL_H__


#define XIMGCONV_LITE_ADDR_AP_CTRL                  0x00
#define XIMGCONV_LITE_ADDR_GIE                      0x04
#define XIMGCONV_LITE_ADDR_IER                      0x08
#define XIMGCONV_LITE_ADDR_ISR                      0x0c
#define XIMGCONV_LITE_ADDR_INPUT_IMAGE_OFFSET_DATA  0x14
#define XIMGCONV_LITE_BITS_INPUT_IMAGE_OFFSET_DATA  32
#define XIMGCONV_LITE_ADDR_OUTPUT_IMAGE_OFFSET_DATA 0x1c
#define XIMGCONV_LITE_BITS_OUTPUT_IMAGE_OFFSET_DATA 32
#define XIMGCONV_LITE_ADDR_FIRST_FLAG_DATA          0x24
#define XIMGCONV_LITE_BITS_FIRST_FLAG_DATA          1


#endif //__DESIGN_KERNEL_H__
